mysql57:
  image : mysql:5.7
  ports:
    - "3306:3306"
  volumes:
    - ~/db/mysql57:/var/lib/mysql
    - ./config.cnf:/etc/mysql/conf.d/config.cnf
  environment:
    TERM: xterm
    APP_ENV: dev
    MYSQL_USER: root 
    MYSQL_PASSWORD: root
    MYSQL_DATABASE: 
    MYSQL_ROOT_PASSWORD: root
  container_name: mysql57
